# target: prerequisites
# 		commands

build:
	@echo "------------------------- Building ------------------------"
	g++ main.cpp -o main
	@echo ""
	@echo "Done!"

execute:
	@echo "------------------ Executing the program -----------------"
	@./main

clean:
	@echo "-------------------------- Clean -------------------------"
	@rm -f main *.o